name: Workflow Dispatch

on:
#   workflow_dispatch:
  schedule:
    - cron: '48 12 * * *' # Runs at 00:00 UTC every day.
  
jobs:
  job1:
    runs-on: ubuntu-latest
    name: Validate changed files
    steps:
      - name: step1
        run: |
          echo "hello I am job1"
  job2:
    runs-on: ubuntu-latest
    name: Job2
    steps:
      - name: step2
        run: |
          echo "$(date)"
